### ISSUE TITLE
connect google API

### ISSUE THREAD

**Issue by hjusassac** [way-seoul/on-my-way#18]
- [x] add columns for corresponding:: latitude & longitude fields on places table
- [x] display google map on the challenge specific page:: 1 marker on the map (#15 )
- [x] display google map on the home page:: multiple markers on the map (#27 )
- [x] display google map on the home page:: pan the map to the current location of the user
- [ ] [use google maps api to select location](https://developers.google.com/maps/documentation/javascript/examples/event-click-latlng):: #77 
- [ ] search by location keyword:: #77

**Comment by polarbearTW** [comment]
I am working on google maps for the home page

**Comment by polarbearTW** [comment]
Just clarified with HJ, I'm working on the preview/landing page now #13 , instead of home page for logged-in users.

**Comment by hjusassac** [comment]
#81 completed multiple markers available from locations on db
